[package]
name = "nexo-tunnel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
futures-io.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
socket2.workspace = true
thiserror.workspace = true
rustls.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
yamux.workspace = true
