import { openServiceEditor } from "./service-actions";
import { expect, test } from "@playwright/test";
import { installApiMocks } from "./api-mocks";

test("账号恢复校验确认密码，失败保留输入，成功返回登录", async ({ page }, testInfo) => {
  const state = await installApiMocks(page, { anonymous: true });
  await page.goto("/");
  await page.getByRole("button", { name: "忘记密码" }).click();
  await page.getByLabel("一次性恢复码").fill("test-one-time-code");
  await page.getByLabel("新密码", { exact: true }).fill("new-password-1234");
  await page.getByLabel("确认新密码").fill("different-password");
  await page.getByRole("button", { name: "重设密码" }).click();
  await expect(page.getByRole("alert")).toContainText("不一致");
  expect(state.calls.some(call => call.path.endsWith("/recover"))).toBeFalsy();
  await page.getByLabel("确认新密码").fill("new-password-1234");
  state.failures.set("POST /api/v1/auth/recover", "恢复码已过期，请重新生成");
  await page.getByRole("button", { name: "重设密码" }).click();
  await expect(page.getByLabel("一次性恢复码")).toHaveValue("test-one-time-code");
  await expect(page.getByRole("alert")).toContainText("过期");
  await page.screenshot({ path: testInfo.outputPath("account-recovery.png") });
  state.failures.clear();
  await page.getByRole("button", { name: "重设密码" }).click();
  await expect(page.getByLabel("用户名")).toHaveValue("admin");
  await expect(page.getByRole("status")).toContainText("密码已重设");
});

test("保存遇到会话过期后重新登录，保留原服务草稿", async ({ page }, testInfo) => {
  const state = await installApiMocks(page);
  await page.goto("/#/services");
  await openServiceEditor(page);
  const editor = page.getByRole("dialog", { name: "创建服务" });
  await editor.getByLabel("服务名称").fill("保留我的草稿");
  await editor.getByLabel("内网端口").fill("8080");
  await editor.getByLabel("主机名").fill("reauth");
  state.failures.set("POST /api/v1/tunnels", "登录已过期"); state.failureStatuses.set("POST /api/v1/tunnels", 401);
  await editor.getByRole("button", { name: "保存服务" }).click();
  const login = page.getByRole("dialog", { name: "登录已过期" });
  await expect(login).toBeVisible();
  await expect(login.getByLabel("用户名")).toHaveValue("admin");
  await login.getByLabel("密码", { exact: true }).fill("a-valid-password");
  state.failures.set("POST /api/v1/auth/login", "用户名或密码错误"); state.failureStatuses.set("POST /api/v1/auth/login", 401);
  await login.getByRole("button", { name: "登录", exact: true }).click();
  await expect(login.getByRole("alert")).toContainText("密码错误");
  await page.screenshot({ path: testInfo.outputPath("reauth-retains-draft.png") });
  state.failures.clear(); state.failureStatuses.clear();
  await login.getByRole("button", { name: "登录", exact: true }).click();
  await expect(login).toBeHidden();
  await expect(editor.getByLabel("服务名称")).toHaveValue("保留我的草稿");
  await expect(editor.getByLabel("内网端口")).toHaveValue("8080");
  await editor.getByRole("button", { name: "保存服务" }).click();
  await expect(editor).toBeHidden();
  expect(state.tunnels.some(item => item.name === "保留我的草稿")).toBeTruthy();
});

test("服务状态自动更新，编辑和后台暂停，返回前台立即刷新", async ({ page }) => {
  const state = await installApiMocks(page);
  await page.clock.install();
  await page.goto("/#/services");
  await expect(page.getByText("媒体中心", { exact: true })).toBeVisible();
  state.tunnels[0].apply_status = "failed"; state.tunnels[0].apply_error = "目标无法连接";
  await page.clock.fastForward(5000);
  await expect(page.getByText("目标无法连接", { exact: true })).toBeVisible();
  await page.evaluate(() => Object.defineProperty(document, "visibilityState", { configurable: true, get: () => "hidden" }));
  const count = () => state.calls.filter(call => call.path === "/api/v1/tunnels").length;
  const before = count(); await page.clock.fastForward(10000); expect(count()).toBe(before);
  state.tunnels[0].name = "前台已更新";
  await page.evaluate(() => { Object.defineProperty(document, "visibilityState", { configurable: true, get: () => "visible" }); document.dispatchEvent(new Event("visibilitychange")); });
  await expect(page.getByText("前台已更新", { exact: true })).toBeVisible();
  await openServiceEditor(page);
  const editing = count(); await page.clock.fastForward(10000); expect(count()).toBe(editing);
});

test("设备恢复凭证绑定原设备，批准前说明撤销旧身份", async ({ page }, testInfo) => {
  await page.clock.install();
  const state = await installApiMocks(page);
  await page.goto("/#/agents/a-1");
  await page.getByRole("region", { name: "设备内部证书" }).locator("summary").click();
  await page.getByRole("button", { name: "恢复设备身份" }).click();
  const recovery = page.getByRole("dialog", { name: "恢复 家庭 Agent 的身份" });
  await recovery.getByRole("button", { name: "生成恢复凭证" }).click();
  await expect(recovery.locator(".token")).toHaveText("recovery-token-for-test");
  expect(state.enrollments.find(item => item.kind === "recovery")?.device_id).toBe("a-1");
  await expect(recovery).toContainText("--recover-identity");
  await page.screenshot({ path: testInfo.outputPath("device-recovery.png") });
  state.enrollments = state.enrollments.filter(item => item.kind === "recovery"); state.enrollments[0].status = "awaiting_approval";
  await recovery.getByRole("button", { name: /^(取消|关闭)$/ }).click();
  await page.getByRole("link", { name: "返回", exact: true }).click();
  await page.clock.fastForward(5000);
  await page.getByRole("button", { name: "批准", exact: true }).click();
  const confirm = page.getByRole("dialog", { name: "批准恢复 家庭 Agent 的身份？" });
  await expect(confirm).toContainText("旧证书及旧连接立即失效");
  await confirm.getByRole("button", { name: "批准恢复", exact: true }).click();
  await expect(confirm).toBeHidden();
  expect(state.devices[0].id).toBe("a-1"); expect(state.tunnels[0].device_id).toBe("a-1");
});
