import { expect, test } from "@playwright/test";
import { installApiMocks } from "./api-mocks";

test("管理员配置额度，停流确认、失败重试与取消限制", async ({ page }, info) => {
  const state = await installApiMocks(page);
  await page.goto("/#/users");
  const user = page.locator(".user-card").filter({ has: page.getByRole("heading", { name: "alice", exact: true }) });
  await user.getByRole("button", { name: "更多" }).click();
  await user.getByRole("button", { name: "流量限制", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "流量限制 · alice", exact: true });
  await expect(dialog).toContainText("80 GiB");
  await dialog.getByLabel("限制方式").selectOption("limited");
  await dialog.getByLabel("月额度（GiB）").fill("100");
  await dialog.getByRole("button", { name: "保存", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(state.quotas.get("alice")?.monthly_limit_bytes).toBe(100 * 1024 ** 3);
  await user.getByRole("button", { name: "更多" }).click();
  await user.getByRole("button", { name: "流量限制", exact: true }).click();
  await dialog.getByLabel("月额度（GiB）").fill("50");
  await expect(dialog).toContainText("保存后将停止该用户全部隧道转发");
  await dialog.getByRole("alert").scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("quota-stop-confirm.png"), fullPage: true });
  state.failures.set("PUT /api/v1/admin/traffic/quota", "额度保存失败");
  await dialog.getByRole("button", { name: "保存并停止转发", exact: true }).click();
  await expect(dialog).toContainText("额度保存失败");
  await expect(dialog.getByLabel("月额度（GiB）")).toHaveValue("50");
  expect(state.quotas.get("alice")?.monthly_limit_bytes).toBe(100 * 1024 ** 3);
  state.failures.clear();
  const sent = page.waitForRequest(req => req.method() === "PUT" && req.url().includes("/traffic/quota"));
  await dialog.getByRole("button", { name: "保存并停止转发", exact: true }).click();
  const request = await sent;
  expect(request.headers()["x-nexo-csrf"]).toBeTruthy();
  expect(new URL(request.url()).searchParams.get("user_id")).toBe("alice");
  await expect(dialog).toHaveCount(0);
  await user.getByRole("button", { name: "更多" }).click();
  await user.getByRole("button", { name: "流量限制", exact: true }).click();
  await dialog.getByLabel("限制方式").selectOption("unlimited");
  await dialog.getByRole("button", { name: "保存", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(state.quotas.get("alice")).toEqual({ monthly_limit_bytes: null, used_bytes: 80 * 1024 ** 3 });
});

test("首页额度独立于重置统计，切换用户及全局不串用", async ({ page }, info) => {
  const state = await installApiMocks(page);
  state.quotas.set("alice", { monthly_limit_bytes: 100 * 1024 ** 3, used_bytes: 80 * 1024 ** 3 });
  await page.goto("/");
  await page.getByRole("button", { name: "流量筛选", exact: true }).click();
  await expect(page.getByRole("region", { name: "本月流量额度", exact: true })).toHaveCount(0);
  await page.getByLabel("统计用户", { exact: true }).selectOption("alice");
  const quota = page.getByRole("region", { name: "本月流量额度", exact: true });
  await expect(quota).toContainText("剩余 20 GiB");
  await expect(quota).toContainText("重置统计不会恢复额度");
  await page.getByRole("button", { name: "重置统计", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "确认重置", exact: true }).click();
  await expect(page.locator(".traffic-usage strong")).toHaveText(["0 B", "0 B", "0 B"]);
  await expect(quota).toContainText("剩余 20 GiB");
  await page.screenshot({ path: info.outputPath("quota-home.png"), fullPage: true });
  await page.getByLabel("统计用户", { exact: true }).selectOption("admin");
  await expect(quota).toContainText("未设置限制");
  state.quotas.set("alice", { monthly_limit_bytes: 80 * 1024 ** 3, used_bytes: 80 * 1024 ** 3 });
  await page.getByLabel("统计用户", { exact: true }).selectOption("alice");
  await expect(quota).toContainText("本月额度已用尽，隧道转发已暂停");
  await expect(quota).toContainText("剩余 0 B");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test("普通用户额度只读，失败保留数据，页面不可见暂停请求", async ({ page }) => {
  const state = await installApiMocks(page);
  await page.route("**/api/v1/auth/status", route => route.fulfill({ json: { initialized: true, authenticated: true, user_id: "alice", username: "alice", role: "tenant", workspace_id: "alice" } }));
  state.failures.set("GET /api/v1/traffic/quota", "额度读取失败");
  await page.goto("/");
  await page.getByRole("button", { name: "流量筛选", exact: true }).click();
  const quota = page.getByRole("region", { name: "本月流量额度", exact: true });
  await expect(quota).toContainText("暂时无法获取额度");
  await expect(quota).not.toContainText("未设置限制");
  await expect(page.getByRole("button", { name: "流量限制", exact: true })).toHaveCount(0);
  expect(state.calls.some(call => call.path.startsWith("/api/v1/admin/"))).toBeFalsy();
  state.failures.clear();
  await page.evaluate(() => window.dispatchEvent(new Event("focus")));
  await expect(quota).toContainText("本月额度消耗 80 GiB");
  state.failures.set("GET /api/v1/traffic/quota", "额度读取失败");
  await page.evaluate(() => window.dispatchEvent(new Event("focus")));
  await expect(quota).toContainText("保留上次数据");
  await expect(quota).toContainText("本月额度消耗 80 GiB");
  await page.clock.install();
  await page.evaluate(() => { Object.defineProperty(document, "visibilityState", { configurable: true, get: () => "hidden" }); document.dispatchEvent(new Event("visibilitychange")); });
  state.calls.length = 0;
  await page.clock.fastForward(65000);
  expect(state.calls.filter(call => call.path.includes("/traffic/quota"))).toHaveLength(0);
});

test("额度迟到响应不能覆盖新用户", async ({ page }) => {
  await installApiMocks(page);
  let release!: () => void;
  const pending = new Promise<void>(resolve => { release = resolve; });
  await page.route("**/api/v1/admin/traffic/quota?user_id=alice", async route => { await pending; await route.fulfill({ json: { monthly_limit_bytes: 100, used_bytes: 100, remaining_bytes: 0, exhausted: true, started_at: 100, period_start: 100, period_end: 200 } }); });
  await page.goto("/");
  await page.getByRole("button", { name: "流量筛选", exact: true }).click();
  const requested = page.waitForRequest("**/api/v1/admin/traffic/quota?user_id=alice");
  await page.getByLabel("统计用户", { exact: true }).selectOption("alice");
  await requested;
  await page.getByLabel("统计用户", { exact: true }).selectOption("admin");
  release();
  const quota = page.getByRole("region", { name: "本月流量额度", exact: true });
  await expect(quota).toContainText("未设置限制");
  await expect(quota).not.toContainText("已暂停");
});
